### ISSUE TITLE
Highlighted item is overlapped by ... icons

### ISSUE THREAD

**Issue by gmisail** [gmisail/dormdesign#40]
When an item is highlighted and you click the drop down, it is overlapped by the ellipses. I attached an image of the issue below. I am assuming that this is related to the animation, since it only occurs when the item is selected in the editor.

![image](https://user-images.githubusercontent.com/8661089/99125756-bbdb3f80-25d2-11eb-9214-0233faf7e6fa.png)

**Comment by metzlr** [comment]
Fixed with #39
